name: taf2
description: light multi purpose toknow list.
version: 2.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  ngdart: ^7.1.1
  meta: 1.9.1
  test: 1.21.1
  http: ^0.13.6
  ngrouter: ^3.1.1
  ngforms: ^4.1.1
  crypto: ^3.0.3
  stream_transform: ^2.1.0
  encrypt: ^5.0.1

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.4
  lints: ^2.0.1

